baseURL = "/"
title = "Abdelrahman's blog ğŸƒ"
languageCode = "en-us"
pagination.pagerSize = 10
enableRobotsTXT = true
theme = "dead-simple"

# Enable tags
[taxonomies]
  tag = "tags"
  category = "categories"

# Top navbar: Home, Posts, Tags
[menu]
  [[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url  = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url  = "/tags/"
    weight = 3
